services:
  server:
    build: ./backend
    container_name: server_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  client:
    build: ./ui
    container_name: client_container
    ports:
      - "8501:8501"
    depends_on:
      - server
    environment:
      - API_URL=http://server:8000